# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.debug=false

# Mapping configuration
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.214
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=oreveins
mod_name=Realistic Ore Veins
mod_license=MIT
mod_version=dev
mod_group_id=com.alcatrazescapee.oreveins
mod_authors=AlcatrazEscapee
mod_description=This mod adds configurable, realistically shaped ore veins for a different resource gathering experience.
